name: Year of the Buffalo
favicon: null
layout_spectrum: 0.4531038391869515
typography_spectrum: 0.33624273422174156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1110'
    - '#b7c395'
    - '#e6e6e6'
    - '#677056'
    - '#8d9775'
  brandStrength: 1
  lightness: 0.17622068291530013
  saturation: 0.1987878978252411
  rhythmicContrast: 0.9841863415203989
purpose: []
